package lexer

var keywords = map[string]TokenKind{
	"ACCESS":             TokKwAccess,
	"AGENT-CAPABILITIES": TokKwAgentCapabilities,
	"APPLICATION":        TokKwApplication,
	"AUGMENTS":           TokKwAugments,
	"BEGIN":              TokKwBegin,
	"BITS":               TokKwBits,
	"CHOICE":             TokKwChoice,
	"CONTACT-INFO":       TokKwContactInfo,
	"CREATION-REQUIRES":  TokKwCreationRequires,
	"Counter":            TokKwCounter,
	"Counter32":          TokKwCounter32,
	"Counter64":          TokKwCounter64,
	"DEFINITIONS":        TokKwDefinitions,
	"DEFVAL":             TokKwDefval,
	"DESCRIPTION":        TokKwDescription,
	"DISPLAY-HINT":       TokKwDisplayHint,
	"END":                TokKwEnd,
	"ENTERPRISE":         TokKwEnterprise,
	"EXPORTS":            TokKwExports,
	"FROM":               TokKwFrom,
	"GROUP":              TokKwGroup,
	"Gauge":              TokKwGauge,
	"Gauge32":            TokKwGauge32,
	"IDENTIFIER":         TokKwIdentifier,
	"IMPLICIT":           TokKwImplicit,
	"IMPLIED":            TokKwImplied,
	"IMPORTS":            TokKwImports,
	"INCLUDES":           TokKwIncludes,
	"INDEX":              TokKwIndex,
	"INTEGER":            TokKwInteger,
	"Integer32":          TokKwInteger32,
	"IpAddress":          TokKwIpAddress,
	"LAST-UPDATED":       TokKwLastUpdated,
	"MACRO":              TokKwMacro,
	"MANDATORY-GROUPS":   TokKwMandatoryGroups,
	"MAX-ACCESS":         TokKwMaxAccess,
	"MIN-ACCESS":         TokKwMinAccess,
	"MODULE":             TokKwModule,
	"MODULE-COMPLIANCE":  TokKwModuleCompliance,
	"MODULE-IDENTITY":    TokKwModuleIdentity,
	"NOTIFICATION-GROUP": TokKwNotificationGroup,
	"NOTIFICATION-TYPE":  TokKwNotificationType,
	"NOTIFICATIONS":      TokKwNotifications,
	"NetworkAddress":     TokKwNetworkAddress,
	"OBJECT":             TokKwObject,
	"OBJECT-GROUP":       TokKwObjectGroup,
	"OBJECT-IDENTITY":    TokKwObjectIdentity,
	"OBJECT-TYPE":        TokKwObjectType,
	"OBJECTS":            TokKwObjects,
	"OCTET":              TokKwOctet,
	"OF":                 TokKwOf,
	"ORGANIZATION":       TokKwOrganization,
	"Opaque":             TokKwOpaque,
	"PRODUCT-RELEASE":    TokKwProductRelease,
	"REFERENCE":          TokKwReference,
	"REVISION":           TokKwRevision,
	"SEQUENCE":           TokKwSequence,
	"SIZE":               TokKwSize,
	"STATUS":             TokKwStatus,
	"STRING":             TokKwString,
	"SUPPORTS":           TokKwSupports,
	"SYNTAX":             TokKwSyntax,
	"TEXTUAL-CONVENTION": TokKwTextualConvention,
	"TRAP-TYPE":          TokKwTrapType,
	"TimeTicks":          TokKwTimeTicks,
	"UNITS":              TokKwUnits,
	"UNIVERSAL":          TokKwUniversal,
	"Unsigned32":         TokKwUnsigned32,
	"VARIABLES":          TokKwVariables,
	"VARIATION":          TokKwVariation,
	"WRITE-SYNTAX":       TokKwWriteSyntax,

	"accessible-for-notify": TokKwAccessibleForNotify,
	"current":               TokKwCurrent,
	"deprecated":            TokKwDeprecated,
	"mandatory":             TokKwMandatory,
	"not-accessible":        TokKwNotAccessible,
	"not-implemented":       TokKwNotImplemented,
	"obsolete":              TokKwObsolete,
	"optional":              TokKwOptional,
	"read-create":           TokKwReadCreate,
	"read-only":             TokKwReadOnly,
	"read-write":            TokKwReadWrite,
	"write-only":            TokKwWriteOnly,
}

// LookupKeyword resolves a keyword string to its token kind.
// Returns (TokError, false) if the text is not a recognized keyword.
func LookupKeyword(text string) (TokenKind, bool) {
	kind, ok := keywords[text]
	if !ok {
		return TokError, false
	}
	return kind, true
}

// ASN.1 reserved keywords that must not be used as identifiers in MIBs.
var forbiddenKeywords = map[string]struct{}{
	"ABSENT":         {},
	"ANY":            {},
	"BIT":            {},
	"BOOLEAN":        {},
	"BY":             {},
	"COMPONENT":      {},
	"COMPONENTS":     {},
	"DEFAULT":        {},
	"DEFINED":        {},
	"ENUMERATED":     {},
	"EXPLICIT":       {},
	"EXTERNAL":       {},
	"FALSE":          {},
	"MAX":            {},
	"MIN":            {},
	"MINUS-INFINITY": {},
	"NULL":           {},
	"OPTIONAL":       {},
	"PLUS-INFINITY":  {},
	"PRESENT":        {},
	"PRIVATE":        {},
	"REAL":           {},
	"SET":            {},
	"TAGS":           {},
	"TRUE":           {},
	"WITH":           {},
}

// IsForbiddenKeyword reports whether text is a reserved ASN.1 keyword.
func IsForbiddenKeyword(text string) bool {
	_, ok := forbiddenKeywords[text]
	return ok
}
